# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'colorize', '~> 0.8.1'

gem 'rubocop', '~> 1.27'

gem 'tty-prompt', '~> 0.23.1'

gem 'crayon', '~> 1.2'

gem 'progress_bar', '~> 1.3', '>= 1.3.3'
